name: tflite_flutter_helper
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 0.4.0
homepage: https://www.github.com/xmartlabs/tflite_flutter_helper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  quiver: ^3.2.1
  path_provider: ^2.1.3
  tflite_flutter: ^0.10.4
  tuple: ^2.0.2
  camera: ^0.11.0+1
  ffi: ^2.1.2
  image: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xmartlabs.tflite_flutter_helper
        pluginClass: TfliteFlutterHelperPlugin
      ios:
        pluginClass: TfliteFlutterHelperPlugin
      linux:
        pluginClass: TfliteFlutterHelperPlugin
      macos:
        pluginClass: TfliteFlutterHelperPlugin
      windows:
        pluginClass: TfliteFlutterHelperPlugin
