name: tflite_flutter_helper
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 0.4.0
homepage: https://www.github.com/xmartlabs/tflite_flutter_helper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  quiver: ^3.2.2
  path_provider: ^2.1.5
  tflite_flutter: ^0.11.0
  tuple: ^2.0.2
  camera: ^0.11.1
  ffi: ^2.1.4
  image: ^4.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xmartlabs.tflite_flutter_helper
        pluginClass: TfliteFlutterHelperPlugin
      ios:
        pluginClass: TfliteFlutterHelperPlugin
      linux:
        pluginClass: TfliteFlutterHelperPlugin
      macos:
        pluginClass: TfliteFlutterHelperPlugin
      windows:
        pluginClass: TfliteFlutterHelperPlugin
